
export interface FAQ {
  question: string;
  answer: string;
  keywords: string[];
}

export const faqs: FAQ[] = [
  {
    question: "How are my meal plans generated?",
    answer: "Your meal plans are generated by our advanced AI. It considers your personal details (age, gender, height, weight), your goals (weight loss, gain, or maintenance), activity level, and dietary preferences to create a personalized and balanced plan just for you.",
    keywords: ["meal plan", "generate", "how", "ai"],
  },
  {
    question: "Can I change my dietary preferences after the initial setup?",
    answer: "Yes, you can update your preferences at any time. Go to your Account page, and you will find a section to edit your nutrition profile, including diet type and food allergies.",
    keywords: ["change", "update", "diet", "preferences", "allergies"],
  },
  {
    question: "Is my personal data secure?",
    answer: "Absolutely. We prioritize your privacy and security. All your data is encrypted and stored securely. We never share your personal information with third parties. For more details, please see our Privacy Policy.",
    keywords: ["data", "security", "privacy", "secure"],
  },
  {
    question: "How do I track my progress?",
    answer: "You can track your progress on the Dashboard. It provides an overview of your achievements, nutrition targets, and trends over time. For more detailed insights, visit the Analytics page.",
    keywords: ["track", "progress", "dashboard", "analytics"],
  },
  {
    question: "What if I don\'t like a suggested meal?",
    answer: "In your meal plan, you can click on any meal to see alternatives or search for a replacement. Our AI will suggest other meals that fit your nutrition targets.",
    keywords: ["replace", "change meal", "don\'t like", "alternative"],
  },
];
