-- Create a table for public profiles using Supabase User ID references
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  age integer,
  weight numeric,
  height numeric,
  activity_level text,
  goal text,
  nutrition jsonb,  -- Store nutrition targets as JSON
  lifestyle jsonb,  -- Store lifestyle preferences as JSON
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;

-- Create policies to ensure users can only see/edit their own data
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Optional: Create a trigger to automatically create a profile entry when a new user signs up
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'name');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create Meals table (Phase 3 Prep)
create table meals (
    id bigint generated by default as identity primary key,
    name text not null,
    calories integer,
    protein integer,
    carbs integer,
    fats integer,
    image text,
    time text,
    tags text[],
    ingredients text[],
    steps text[]
);

alter table meals enable row level security;

create policy "Meals are viewable by everyone"
  on meals for select
  using ( true );

-- (Only admins or service role can insert/update meals - typically)
